INSERT IGNORE INTO email_templates (slug, name, subject, html_body, from_name, from_email, to_type, to_address, variables, is_active) VALUES
('contact-form', 'הודעת יצירת קשר', 'יצירת קשר: {{category}} - {{userName}}',
'<div dir="rtl" style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #1e293b, #0f172a); padding: 24px; border-radius: 12px 12px 0 0;"><h2 style="color: #fbbf24; margin: 0;">הודעה חדשה מטופס יצירת קשר</h2></div><div style="background: #fff; padding: 24px; border: 1px solid #e2e8f0;"><table style="border-collapse: collapse; width: 100%;"><tr><td style="padding: 10px 12px; border-bottom: 1px solid #f1f5f9; font-weight: bold; color: #475569;">קטגוריה</td><td style="padding: 10px 12px; border-bottom: 1px solid #f1f5f9;">{{category}}</td></tr><tr><td style="padding: 10px 12px; border-bottom: 1px solid #f1f5f9; font-weight: bold; color: #475569;">שם</td><td style="padding: 10px 12px; border-bottom: 1px solid #f1f5f9;">{{userName}}</td></tr><tr><td style="padding: 10px 12px; border-bottom: 1px solid #f1f5f9; font-weight: bold; color: #475569;">אימייל</td><td style="padding: 10px 12px; border-bottom: 1px solid #f1f5f9;">{{userEmail}}</td></tr><tr><td style="padding: 10px 12px; font-weight: bold; color: #475569;">עמוד</td><td style="padding: 10px 12px;">{{pageUrl}}</td></tr></table><div style="margin-top: 20px; padding: 16px; background: #f8fafc; border-radius: 8px; border-right: 4px solid #fbbf24;"><p style="margin: 0; white-space: pre-wrap; color: #1e293b;">{{message}}</p></div></div><div style="background: #f1f5f9; padding: 16px; text-align: center; border-radius: 0 0 12px 12px; font-size: 12px; color: #94a3b8;">Juhuri Heritage - jun-juhuri.com</div></div>',
'Juhuri Heritage', 'info@jun-juhuri.com', 'admin', 'jun.juhuri@gmail.com',
'["category", "userName", "userEmail", "message", "pageUrl"]', 1),

('welcome', 'ברוכים הבאים', 'ברוכים הבאים ל-Juhuri Heritage, {{userName}}!',
'<div dir="rtl" style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #1e293b, #0f172a); padding: 32px; border-radius: 12px 12px 0 0; text-align: center;"><h1 style="color: #fbbf24; margin: 0; font-size: 24px;">ברוכים הבאים!</h1><p style="color: #94a3b8; margin: 8px 0 0;">הצטרפת למשפחת Juhuri Heritage</p></div><div style="background: #fff; padding: 32px; border: 1px solid #e2e8f0;"><p style="color: #1e293b; font-size: 16px;">שלום {{userName}},</p><p style="color: #475569; line-height: 1.6;">שמחים שהצטרפת לקהילה שלנו! כאן תוכל/י לגלות את עולם השפה והתרבות של יהודי קווקז.</p><div style="text-align: center; margin: 24px 0;"><a href="https://jun-juhuri.com/dictionary" style="background: #fbbf24; color: #1e293b; padding: 12px 32px; border-radius: 8px; text-decoration: none; font-weight: bold;">התחילו לגלות</a></div></div><div style="background: #f1f5f9; padding: 16px; text-align: center; border-radius: 0 0 12px 12px; font-size: 12px; color: #94a3b8;">Juhuri Heritage - jun-juhuri.com</div></div>',
'Juhuri Heritage', 'info@jun-juhuri.com', 'user', NULL,
'["userName"]', 0),

('password-reset', 'איפוס סיסמה', 'איפוס סיסמה - Juhuri Heritage',
'<div dir="rtl" style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #1e293b, #0f172a); padding: 24px; border-radius: 12px 12px 0 0;"><h2 style="color: #fbbf24; margin: 0;">איפוס סיסמה</h2></div><div style="background: #fff; padding: 32px; border: 1px solid #e2e8f0;"><p style="color: #1e293b;">שלום {{userName}},</p><p style="color: #475569;">קיבלנו בקשה לאיפוס הסיסמה שלך. לחצ/י על הכפתור:</p><div style="text-align: center; margin: 24px 0;"><a href="{{resetUrl}}" style="background: #fbbf24; color: #1e293b; padding: 12px 32px; border-radius: 8px; text-decoration: none; font-weight: bold;">איפוס סיסמה</a></div><p style="color: #94a3b8; font-size: 13px;">הקישור תקף ל-60 דקות. אם לא ביקשת איפוס, ניתן להתעלם ממייל זה.</p></div><div style="background: #f1f5f9; padding: 16px; text-align: center; border-radius: 0 0 12px 12px; font-size: 12px; color: #94a3b8;">Juhuri Heritage - jun-juhuri.com</div></div>',
'Juhuri Heritage', 'info@jun-juhuri.com', 'user', NULL,
'["userName", "resetUrl"]', 0),

('suggestion-approved', 'הצעה אושרה', 'ההצעה שלך אושרה!',
'<div dir="rtl" style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #1e293b, #0f172a); padding: 24px; border-radius: 12px 12px 0 0;"><h2 style="color: #22c55e; margin: 0;">ההצעה שלך אושרה!</h2></div><div style="background: #fff; padding: 32px; border: 1px solid #e2e8f0;"><p style="color: #1e293b;">שלום {{userName}},</p><p style="color: #475569;">שמחים לעדכן שההצעה שלך למילה <strong>{{term}}</strong> אושרה והתווספה למילון.</p><p style="color: #475569;">תודה על התרומה לשימור השפה!</p><div style="text-align: center; margin: 24px 0;"><a href="https://jun-juhuri.com/word/{{term}}" style="background: #22c55e; color: #fff; padding: 12px 32px; border-radius: 8px; text-decoration: none; font-weight: bold;">צפייה במילה</a></div></div><div style="background: #f1f5f9; padding: 16px; text-align: center; border-radius: 0 0 12px 12px; font-size: 12px; color: #94a3b8;">Juhuri Heritage - jun-juhuri.com</div></div>',
'Juhuri Heritage', 'info@jun-juhuri.com', 'user', NULL,
'["userName", "term"]', 0),

('suggestion-rejected', 'הצעה נדחתה', 'עדכון לגבי ההצעה שלך',
'<div dir="rtl" style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #1e293b, #0f172a); padding: 24px; border-radius: 12px 12px 0 0;"><h2 style="color: #fbbf24; margin: 0;">עדכון לגבי ההצעה שלך</h2></div><div style="background: #fff; padding: 32px; border: 1px solid #e2e8f0;"><p style="color: #1e293b;">שלום {{userName}},</p><p style="color: #475569;">לצערנו ההצעה שלך למילה <strong>{{term}}</strong> לא אושרה.</p><p style="color: #475569;">סיבה: {{reason}}</p><p style="color: #475569;">אנחנו מעודדים אותך להמשיך לתרום! כל הצעה עוזרת לנו לשמר את השפה.</p></div><div style="background: #f1f5f9; padding: 16px; text-align: center; border-radius: 0 0 12px 12px; font-size: 12px; color: #94a3b8;">Juhuri Heritage - jun-juhuri.com</div></div>',
'Juhuri Heritage', 'info@jun-juhuri.com', 'user', NULL,
'["userName", "term", "reason"]', 0),

('suggestion-submitted', 'הצעת תרגום חדשה', 'הצעת תרגום חדשה מ-{{userName}}',
'<div dir="rtl" style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #1e293b, #0f172a); padding: 24px; border-radius: 12px 12px 0 0;"><h2 style="color: #fbbf24; margin: 0;">הצעת תרגום חדשה</h2></div><div style="background: #fff; padding: 32px; border: 1px solid #e2e8f0;"><p style="color: #1e293b;">הצעה חדשה התקבלה מ-<strong>{{userName}}</strong>:</p><table style="border-collapse: collapse; width: 100%;"><tr><td style="padding: 10px 12px; border-bottom: 1px solid #f1f5f9; font-weight: bold; color: #475569;">ערך</td><td style="padding: 10px 12px; border-bottom: 1px solid #f1f5f9;">{{entryId}}</td></tr><tr><td style="padding: 10px 12px; border-bottom: 1px solid #f1f5f9; font-weight: bold; color: #475569;">ניב</td><td style="padding: 10px 12px; border-bottom: 1px solid #f1f5f9;">{{dialect}}</td></tr><tr><td style="padding: 10px 12px; font-weight: bold; color: #475569;">תרגום</td><td style="padding: 10px 12px;">{{hebrew}}</td></tr></table><div style="text-align: center; margin: 24px 0;"><a href="https://jun-juhuri.com/admin" style="background: #fbbf24; color: #1e293b; padding: 12px 32px; border-radius: 8px; text-decoration: none; font-weight: bold;">לוח ניהול</a></div></div><div style="background: #f1f5f9; padding: 16px; text-align: center; border-radius: 0 0 12px 12px; font-size: 12px; color: #94a3b8;">Juhuri Heritage - jun-juhuri.com</div></div>',
'Juhuri Heritage', 'info@jun-juhuri.com', 'admin', 'jun.juhuri@gmail.com',
'["userName", "entryId", "dialect", "hebrew"]', 1),

('comment-approved', 'תגובה אושרה', 'התגובה שלך אושרה!',
'<div dir="rtl" style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #1e293b, #0f172a); padding: 24px; border-radius: 12px 12px 0 0;"><h2 style="color: #22c55e; margin: 0;">התגובה שלך אושרה!</h2></div><div style="background: #fff; padding: 32px; border: 1px solid #e2e8f0;"><p style="color: #475569;">התגובה שהשארת אושרה ופורסמה באתר.</p><p style="color: #475569;">תודה על התרומה לקהילה!</p><div style="text-align: center; margin: 24px 0;"><a href="https://jun-juhuri.com/dictionary" style="background: #22c55e; color: #fff; padding: 12px 32px; border-radius: 8px; text-decoration: none; font-weight: bold;">לאתר</a></div></div><div style="background: #f1f5f9; padding: 16px; text-align: center; border-radius: 0 0 12px 12px; font-size: 12px; color: #94a3b8;">Juhuri Heritage - jun-juhuri.com</div></div>',
'Juhuri Heritage', 'info@jun-juhuri.com', 'user', NULL,
'["commentId"]', 1),

('recipe-submitted', 'מתכון חדש הוגש', 'מתכון חדש מ-{{userName}}: {{recipeTitle}}',
'<div dir="rtl" style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #1e293b, #0f172a); padding: 24px; border-radius: 12px 12px 0 0;"><h2 style="color: #fbbf24; margin: 0;">מתכון חדש ממתין לאישור</h2></div><div style="background: #fff; padding: 32px; border: 1px solid #e2e8f0;"><p style="color: #1e293b;"><strong>{{userName}}</strong> הגיש/ה מתכון חדש:</p><div style="padding: 16px; background: #f8fafc; border-radius: 8px; border-right: 4px solid #fbbf24; margin: 16px 0;"><p style="margin: 0; color: #1e293b; font-size: 18px; font-weight: bold;">{{recipeTitle}}</p></div><div style="text-align: center; margin: 24px 0;"><a href="https://jun-juhuri.com/admin" style="background: #fbbf24; color: #1e293b; padding: 12px 32px; border-radius: 8px; text-decoration: none; font-weight: bold;">אישור מתכון</a></div></div><div style="background: #f1f5f9; padding: 16px; text-align: center; border-radius: 0 0 12px 12px; font-size: 12px; color: #94a3b8;">Juhuri Heritage - jun-juhuri.com</div></div>',
'Juhuri Heritage', 'info@jun-juhuri.com', 'admin', 'jun.juhuri@gmail.com',
'["userName", "recipeTitle", "recipeId"]', 1),

('recipe-approved', 'מתכון אושר', 'המתכון שלך אושר!',
'<div dir="rtl" style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #1e293b, #0f172a); padding: 24px; border-radius: 12px 12px 0 0;"><h2 style="color: #22c55e; margin: 0;">המתכון שלך אושר!</h2></div><div style="background: #fff; padding: 32px; border: 1px solid #e2e8f0;"><p style="color: #1e293b;">שלום {{userName}},</p><p style="color: #475569;">שמחים לעדכן שהמתכון <strong>{{recipeTitle}}</strong> אושר ופורסם באתר.</p><p style="color: #475569;">תודה על השיתוף!</p><div style="text-align: center; margin: 24px 0;"><a href="https://jun-juhuri.com/recipes" style="background: #22c55e; color: #fff; padding: 12px 32px; border-radius: 8px; text-decoration: none; font-weight: bold;">צפייה במתכון</a></div></div><div style="background: #f1f5f9; padding: 16px; text-align: center; border-radius: 0 0 12px 12px; font-size: 12px; color: #94a3b8;">Juhuri Heritage - jun-juhuri.com</div></div>',
'Juhuri Heritage', 'info@jun-juhuri.com', 'user', NULL,
'["userName", "recipeTitle"]', 1),

('entry-approved', 'ערך מילוני אושר', 'המילה שהגשת אושרה!',
'<div dir="rtl" style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #1e293b, #0f172a); padding: 24px; border-radius: 12px 12px 0 0;"><h2 style="color: #22c55e; margin: 0;">הערך שלך אושר!</h2></div><div style="background: #fff; padding: 32px; border: 1px solid #e2e8f0;"><p style="color: #475569;">המילה <strong>{{term}}</strong> אושרה והתווספה למילון.</p><p style="color: #475569;">תודה על התרומה לשימור השפה!</p><div style="text-align: center; margin: 24px 0;"><a href="https://jun-juhuri.com/word/{{term}}" style="background: #22c55e; color: #fff; padding: 12px 32px; border-radius: 8px; text-decoration: none; font-weight: bold;">צפייה במילה</a></div></div><div style="background: #f1f5f9; padding: 16px; text-align: center; border-radius: 0 0 12px 12px; font-size: 12px; color: #94a3b8;">Juhuri Heritage - jun-juhuri.com</div></div>',
'Juhuri Heritage', 'info@jun-juhuri.com', 'user', NULL,
'["term"]', 1),

('family-link-request', 'בקשת קישור משפחתי', 'בקשת קישור חדשה מ-{{userName}}',
'<div dir="rtl" style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #1e293b, #0f172a); padding: 24px; border-radius: 12px 12px 0 0;"><h2 style="color: #fbbf24; margin: 0;">בקשת קישור משפחתי</h2></div><div style="background: #fff; padding: 32px; border: 1px solid #e2e8f0;"><p style="color: #1e293b;">שלום {{userName}},</p><p style="color: #475569;">מישהו ביקש לקשר את הרשומה שלו לרשומה משפחתית שלך. בקר/י באתר כדי לאשר או לדחות.</p><div style="text-align: center; margin: 24px 0;"><a href="https://jun-juhuri.com/family" style="background: #fbbf24; color: #1e293b; padding: 12px 32px; border-radius: 8px; text-decoration: none; font-weight: bold;">צפייה בבקשה</a></div></div><div style="background: #f1f5f9; padding: 16px; text-align: center; border-radius: 0 0 12px 12px; font-size: 12px; color: #94a3b8;">Juhuri Heritage - jun-juhuri.com</div></div>',
'Juhuri Heritage', 'info@jun-juhuri.com', 'user', NULL,
'["userName"]', 1),

('family-link-approved', 'קישור משפחתי אושר', 'בקשת הקישור שלך אושרה!',
'<div dir="rtl" style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #1e293b, #0f172a); padding: 24px; border-radius: 12px 12px 0 0;"><h2 style="color: #22c55e; margin: 0;">הקישור אושר!</h2></div><div style="background: #fff; padding: 32px; border: 1px solid #e2e8f0;"><p style="color: #1e293b;">שלום {{userName}},</p><p style="color: #475569;">בקשת הקישור המשפחתי שלך אושרה. הרשומות מחוברות כעת בעץ המשפחה.</p><div style="text-align: center; margin: 24px 0;"><a href="https://jun-juhuri.com/family" style="background: #22c55e; color: #fff; padding: 12px 32px; border-radius: 8px; text-decoration: none; font-weight: bold;">לעץ המשפחה</a></div></div><div style="background: #f1f5f9; padding: 16px; text-align: center; border-radius: 0 0 12px 12px; font-size: 12px; color: #94a3b8;">Juhuri Heritage - jun-juhuri.com</div></div>',
'Juhuri Heritage', 'info@jun-juhuri.com', 'user', NULL,
'["userName"]', 1),

('family-link-rejected', 'קישור משפחתי נדחה', 'עדכון לגבי בקשת הקישור',
'<div dir="rtl" style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #1e293b, #0f172a); padding: 24px; border-radius: 12px 12px 0 0;"><h2 style="color: #fbbf24; margin: 0;">עדכון לגבי בקשת הקישור</h2></div><div style="background: #fff; padding: 32px; border: 1px solid #e2e8f0;"><p style="color: #1e293b;">שלום {{userName}},</p><p style="color: #475569;">בקשת הקישור המשפחתי שלך לא אושרה. אם את/ה חושב/ת שמדובר בטעות, ניתן ליצור קשר.</p></div><div style="background: #f1f5f9; padding: 16px; text-align: center; border-radius: 0 0 12px 12px; font-size: 12px; color: #94a3b8;">Juhuri Heritage - jun-juhuri.com</div></div>',
'Juhuri Heritage', 'info@jun-juhuri.com', 'user', NULL,
'["userName"]', 1),

('word-submitted', 'מילה חדשה הוגשה', 'מילה חדשה: {{term}}',
'<div dir="rtl" style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #1e293b, #0f172a); padding: 24px; border-radius: 12px 12px 0 0;"><h2 style="color: #fbbf24; margin: 0;">מילה חדשה נוספה למילון</h2></div><div style="background: #fff; padding: 32px; border: 1px solid #e2e8f0;"><p style="color: #1e293b;"><strong>{{userName}}</strong> הוסיף/ה מילה חדשה:</p><div style="padding: 16px; background: #f8fafc; border-radius: 8px; border-right: 4px solid #fbbf24; margin: 16px 0;"><p style="margin: 0; color: #1e293b; font-size: 20px; font-weight: bold;">{{term}}</p></div><p style="color: #94a3b8; font-size: 13px;">המילה ממתינה לתרגום מהקהילה.</p><div style="text-align: center; margin: 24px 0;"><a href="https://jun-juhuri.com/admin" style="background: #fbbf24; color: #1e293b; padding: 12px 32px; border-radius: 8px; text-decoration: none; font-weight: bold;">לוח ניהול</a></div></div><div style="background: #f1f5f9; padding: 16px; text-align: center; border-radius: 0 0 12px 12px; font-size: 12px; color: #94a3b8;">Juhuri Heritage - jun-juhuri.com</div></div>',
'Juhuri Heritage', 'info@jun-juhuri.com', 'admin', 'jun.juhuri@gmail.com',
'["userName", "term"]', 1),

('field-suggested', 'הצעת תיקון שדה', 'הצעת תיקון שדה: {{term}} — {{fieldName}}',
'<div dir="rtl" style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #1e293b, #0f172a); padding: 24px; border-radius: 12px 12px 0 0;"><h2 style="color: #fbbf24; margin: 0;">הצעת תיקון שדה</h2></div><div style="background: #fff; padding: 32px; border: 1px solid #e2e8f0;"><p style="color: #1e293b;"><strong>{{userName}}</strong> הציע/ה תיקון:</p><table style="border-collapse: collapse; width: 100%;"><tr><td style="padding: 10px 12px; border-bottom: 1px solid #f1f5f9; font-weight: bold; color: #475569;">מילה</td><td style="padding: 10px 12px; border-bottom: 1px solid #f1f5f9;">{{term}}</td></tr><tr><td style="padding: 10px 12px; border-bottom: 1px solid #f1f5f9; font-weight: bold; color: #475569;">שדה</td><td style="padding: 10px 12px; border-bottom: 1px solid #f1f5f9;">{{fieldName}}</td></tr><tr><td style="padding: 10px 12px; font-weight: bold; color: #475569;">ערך מוצע</td><td style="padding: 10px 12px;">{{suggestedValue}}</td></tr></table><div style="text-align: center; margin: 24px 0;"><a href="https://jun-juhuri.com/admin" style="background: #fbbf24; color: #1e293b; padding: 12px 32px; border-radius: 8px; text-decoration: none; font-weight: bold;">לוח ניהול</a></div></div><div style="background: #f1f5f9; padding: 16px; text-align: center; border-radius: 0 0 12px 12px; font-size: 12px; color: #94a3b8;">Juhuri Heritage - jun-juhuri.com</div></div>',
'Juhuri Heritage', 'info@jun-juhuri.com', 'admin', 'jun.juhuri@gmail.com',
'["userName", "term", "fieldName", "suggestedValue"]', 1),

('merge-suggested', 'הצעת מיזוג כפולים', 'הצעת מיזוג: ערך {{entryIdA}} ↔ {{entryIdB}}',
'<div dir="rtl" style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #1e293b, #0f172a); padding: 24px; border-radius: 12px 12px 0 0;"><h2 style="color: #fbbf24; margin: 0;">הצעת מיזוג כפולים</h2></div><div style="background: #fff; padding: 32px; border: 1px solid #e2e8f0;"><p style="color: #1e293b;"><strong>{{userName}}</strong> מציע/ה למזג שני ערכים:</p><table style="border-collapse: collapse; width: 100%;"><tr><td style="padding: 10px 12px; border-bottom: 1px solid #f1f5f9; font-weight: bold; color: #475569;">ערך א׳</td><td style="padding: 10px 12px; border-bottom: 1px solid #f1f5f9;">#{{entryIdA}}</td></tr><tr><td style="padding: 10px 12px; border-bottom: 1px solid #f1f5f9; font-weight: bold; color: #475569;">ערך ב׳</td><td style="padding: 10px 12px; border-bottom: 1px solid #f1f5f9;">#{{entryIdB}}</td></tr><tr><td style="padding: 10px 12px; font-weight: bold; color: #475569;">סיבה</td><td style="padding: 10px 12px;">{{reason}}</td></tr></table><div style="text-align: center; margin: 24px 0;"><a href="https://jun-juhuri.com/admin" style="background: #fbbf24; color: #1e293b; padding: 12px 32px; border-radius: 8px; text-decoration: none; font-weight: bold;">לוח ניהול</a></div></div><div style="background: #f1f5f9; padding: 16px; text-align: center; border-radius: 0 0 12px 12px; font-size: 12px; color: #94a3b8;">Juhuri Heritage - jun-juhuri.com</div></div>',
'Juhuri Heritage', 'info@jun-juhuri.com', 'admin', 'jun.juhuri@gmail.com',
'["userName", "entryIdA", "entryIdB", "reason"]', 1),

('comment-submitted', 'תגובת אורח חדשה', 'תגובה ממתינה לאישור מ-{{guestName}}',
'<div dir="rtl" style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #1e293b, #0f172a); padding: 24px; border-radius: 12px 12px 0 0;"><h2 style="color: #fbbf24; margin: 0;">תגובה ממתינה לאישור</h2></div><div style="background: #fff; padding: 32px; border: 1px solid #e2e8f0;"><p style="color: #1e293b;">תגובה חדשה מ-<strong>{{guestName}}</strong> ממתינה לאישור:</p><table style="border-collapse: collapse; width: 100%;"><tr><td style="padding: 10px 12px; border-bottom: 1px solid #f1f5f9; font-weight: bold; color: #475569;">ערך</td><td style="padding: 10px 12px; border-bottom: 1px solid #f1f5f9;">#{{entryId}}</td></tr><tr><td style="padding: 10px 12px; font-weight: bold; color: #475569;">תגובה</td><td style="padding: 10px 12px;">#{{commentId}}</td></tr></table><div style="text-align: center; margin: 24px 0;"><a href="https://jun-juhuri.com/admin" style="background: #fbbf24; color: #1e293b; padding: 12px 32px; border-radius: 8px; text-decoration: none; font-weight: bold;">אישור תגובות</a></div></div><div style="background: #f1f5f9; padding: 16px; text-align: center; border-radius: 0 0 12px 12px; font-size: 12px; color: #94a3b8;">Juhuri Heritage - jun-juhuri.com</div></div>',
'Juhuri Heritage', 'info@jun-juhuri.com', 'admin', 'jun.juhuri@gmail.com',
'["guestName", "entryId", "commentId"]', 1),

('comment-rejected', 'תגובה נדחתה', 'עדכון לגבי התגובה שלך',
'<div dir="rtl" style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #1e293b, #0f172a); padding: 24px; border-radius: 12px 12px 0 0;"><h2 style="color: #fbbf24; margin: 0;">עדכון לגבי התגובה שלך</h2></div><div style="background: #fff; padding: 32px; border: 1px solid #e2e8f0;"><p style="color: #1e293b;">שלום {{userName}},</p><p style="color: #475569;">לצערנו התגובה שהשארת לא אושרה לפרסום.</p><p style="color: #475569;">אנחנו מעודדים אותך להמשיך להשתתף בקהילה!</p></div><div style="background: #f1f5f9; padding: 16px; text-align: center; border-radius: 0 0 12px 12px; font-size: 12px; color: #94a3b8;">Juhuri Heritage - jun-juhuri.com</div></div>',
'Juhuri Heritage', 'info@jun-juhuri.com', 'user', NULL,
'["userName"]', 1),

('example-submitted', 'פתגם חדש הוגש', 'פתגם חדש מ-{{userName}} — {{term}}',
'<div dir="rtl" style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #1e293b, #0f172a); padding: 24px; border-radius: 12px 12px 0 0;"><h2 style="color: #fbbf24; margin: 0;">פתגם/דוגמה חדש/ה</h2></div><div style="background: #fff; padding: 32px; border: 1px solid #e2e8f0;"><p style="color: #1e293b;"><strong>{{userName}}</strong> הגיש/ה פתגם חדש עבור המילה <strong>{{term}}</strong>.</p><div style="text-align: center; margin: 24px 0;"><a href="https://jun-juhuri.com/admin" style="background: #fbbf24; color: #1e293b; padding: 12px 32px; border-radius: 8px; text-decoration: none; font-weight: bold;">אישור פתגמים</a></div></div><div style="background: #f1f5f9; padding: 16px; text-align: center; border-radius: 0 0 12px 12px; font-size: 12px; color: #94a3b8;">Juhuri Heritage - jun-juhuri.com</div></div>',
'Juhuri Heritage', 'info@jun-juhuri.com', 'admin', 'jun.juhuri@gmail.com',
'["userName", "term", "entryId"]', 1),

('example-approved', 'פתגם אושר', 'הפתגם שלך אושר!',
'<div dir="rtl" style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #1e293b, #0f172a); padding: 24px; border-radius: 12px 12px 0 0;"><h2 style="color: #22c55e; margin: 0;">הפתגם שלך אושר!</h2></div><div style="background: #fff; padding: 32px; border: 1px solid #e2e8f0;"><p style="color: #1e293b;">שלום {{userName}},</p><p style="color: #475569;">הפתגם שהגשת אושר ופורסם באתר.</p><p style="color: #475569;">תודה על התרומה לשימור המסורת!</p><div style="text-align: center; margin: 24px 0;"><a href="https://jun-juhuri.com/dictionary" style="background: #22c55e; color: #fff; padding: 12px 32px; border-radius: 8px; text-decoration: none; font-weight: bold;">לאתר</a></div></div><div style="background: #f1f5f9; padding: 16px; text-align: center; border-radius: 0 0 12px 12px; font-size: 12px; color: #94a3b8;">Juhuri Heritage - jun-juhuri.com</div></div>',
'Juhuri Heritage', 'info@jun-juhuri.com', 'user', NULL,
'["userName"]', 1),

('newsletter', 'ניוזלטר', '{{subject}}',
'<div dir="rtl" style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #1e293b, #0f172a); padding: 32px; border-radius: 12px 12px 0 0; text-align: center;"><h1 style="color: #fbbf24; margin: 0;">Juhuri Heritage</h1></div><div style="background: #fff; padding: 32px; border: 1px solid #e2e8f0;">{{content}}</div><div style="background: #f1f5f9; padding: 16px; text-align: center; border-radius: 0 0 12px 12px; font-size: 12px; color: #94a3b8;">Juhuri Heritage - jun-juhuri.com</div></div>',
'Juhuri Heritage', 'info@jun-juhuri.com', 'custom', NULL,
'["subject", "content", "unsubscribeUrl"]', 0);
